---
title: "Curriculum Vitae - Helena R. S. D'Espindula"
author: "helena.despindula@gmail.com"
date: "`r format(Sys.time(), '%d/%m/%Y')`"
output: pdf_document ##: extra_dependencies: ["colortbl", "xcolor"]
papersize: a4
documentclass: article
linestretch: 1.15
fontsize: 10pt
margin-left: 1cm
margin-right: 1.5cm
margin-top: 2cm
margin-bottom: 2cm
adjusting: b
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(knitr.table.format = "latex")

idioma_cv = "PT"
modelo = 1

library(stringr)
library(tidyverse)
library(kableExtra)
```

## Dados pessoais

```{r xml}

file_name <- "CV-2021-dados_pessoais.csv"

tabela_imprimir <- read.csv2(file_name, sep = ";", header = FALSE)


kbl(tabela_imprimir, col.names = NULL, booktabs=T)%>% 
  kable_styling(latex_options=c("striped","scale_down","hold_position"), full_width=T)%>% 
  column_spec(1,width="4cm")

#View(tabela_imprimir)

#knitr::kable(tabela_imprimir, align = "ll", col.names = NULL)

```
### Links complementares

```{r links}

file_name <- "CV-2021-links.csv"

tabela_imprimir <- read.csv2(file_name, sep = ";", header = FALSE)

kbl(tabela_imprimir, col.names = NULL, booktabs=T)%>% 
  kable_styling(latex_options = c("scale_down", "striped", "hold_position"), full_width=T)%>% 
  column_spec(1, width="4cm")


#View(tabela_imprimir)

#knitr::kable(tabela_imprimir, align = "ll", col.names = NULL)

```

## Formacao

```{r csv}

file_name <- "CV-2021-formatacao2.csv"

tabela_mae <- read.csv2(file_name, sep = ";", header = TRUE)

tabela_imprimir <- matrix(data = NA, nrow = 3, ncol = 3)

for (i in 1:3) {
  if (idioma_cv == "PT") {
    if (modelo == 1) {
      tabela_imprimir[i,1] <- stringr::str_glue(tabela_mae[i,"ano_inicio"], " até ", tabela_mae[i,"ano_fim"], .sep = "")
      tabela_imprimir[i,2] <- stringr::str_glue(tabela_mae[i,"tipo_PT"],  " ", tabela_mae[i,"conec_PT"], " ",  tabela_mae[i,"nome_PT"], .sep = "")
      tabela_imprimir[i,3] <- stringr::str_glue(tabela_mae[i,"ies_nome"], " (", tabela_mae[i,"ies_sigla"], ")", .sep = "")
    }
  }
}

View(tabela_imprimir)


kbl(tabela_imprimir[1:3, 1:2], col.names = NULL, booktabs = T) %>%
  kable_styling(latex_options = c( "striped" , "scale_down", "hold_position"), full_width = T, stripe_color = "gray") %>%
  column_spec(1, width = "3.5cm") %>%
  pack_rows(tabela_imprimir[1,3],1, 2)%>% 
  pack_rows(tabela_imprimir[3,3],3, 3)


#knitr::kable(tabela_imprimir, align = "llll", col.names = NULL)
```
## Experiencia profissional

```{r}
file_name <- "CV-2021-exp_prof.csv"

tabela_mae <- read.csv2(file_name, sep = ";", header = TRUE)

View(tabela_mae)

tabela_imprimir <- matrix(data = NA, nrow = (3*nrow(tabela_mae)), ncol = 3)

h <-1

for (i in 1:nrow(tabela_mae)) { # i conta linha original e h linha destibo
  
  if (idioma_cv == "PT") {
    
    if (modelo == 1) {
      tabela_imprimir[h, 1] <-
        stringr::str_glue(tabela_mae[i, "ano_inicio"], " até ", tabela_mae[i, "ano_fim"], .sep = "")
      tabela_imprimir[h, 2] <- tabela_mae[i, "cargo"]
      tabela_imprimir[h, 3] <-
        stringr::str_glue(tabela_mae[i, "empresa_nome"], " (", tabela_mae[i, "empresa_link"], ")", .sep = "")
      h <- h + 1
      if(is.na(tabela_mae[i, "atrib1"]) == FALSE) {
        tabela_imprimir[h, 1] <- ""
        tabela_imprimir[h, 2] <- tabela_mae[i, "atrib1"]
        h <- h + 1
      }
    }
    else if (modelo == 2) {
      tabela_imprimir[h, 1] <-
        stringr::str_glue(tabela_mae[i, "ano_inicio"], " até ", tabela_mae[i, "ano_fim"], .sep = "")
      tabela_imprimir[h, 2] <- tabela_mae[i, "cargo"]
      h <- h + 1
      tabela_imprimir[h, 1] <- ""
      tabela_imprimir[h, 2] <-
        stringr::str_glue(tabela_mae[i, "empresa_nome"], " (", tabela_mae[i, "empresa_link"], ")", .sep = "")
      h <- h + 1
      if(is.na(tabela_mae[i, "atrib1"]) == FALSE) {
        tabela_imprimir[h, 1] <- ""
        tabela_imprimir[h, 2] <- tabela_mae[i, "atrib1"]
        h <- h + 1
      }
    }
  }
}

View(tabela_imprimir)





kbl(tabela_imprimir[,1:2], col.names = NULL, booktabs = T) %>%
  
    kable_styling(latex_options = c( "striped" , "scale_down", "hold_position"), full_width = T, stripe_color = "gray") %>%
  
    column_spec(1, width = "3.5cm") %>%
    pack_rows(tabela_imprimir[1,3],1, 1)%>% 
    pack_rows(tabela_imprimir[3,3],3, 4)%>%
    pack_rows(tabela_imprimir[5,3],5, 6)%>%
    pack_rows(tabela_imprimir[7,3],7, 8)%>%
    pack_rows(tabela_imprimir[9,3],9, 10)%>%
    pack_rows(tabela_imprimir[11,3],11, 12)%>%
    pack_rows(tabela_imprimir[13,3],13, 16)
  
  
```


## Publicações

### Artigos científicos

```{r}

```

### Capitulos de livro

```{r}

```


## Ferramentas de Informatica

```{r}

```



## Idiomas

```{r}

```



